# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DigitalTwinInterfacesPatchInterfacesValuePropertiesValue(Model):
    """DigitalTwinInterfacesPatchInterfacesValuePropertiesValue.

    :param desired:
    :type desired:
     ~protocol.models.DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired
    """

    _attribute_map = {
        "desired": {
            "key": "desired",
            "type": "DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired",
        }
    }

    def __init__(self, *, desired=None, **kwargs) -> None:
        super(DigitalTwinInterfacesPatchInterfacesValuePropertiesValue, self).__init__(**kwargs)
        self.desired = desired
