# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Interface(Model):
    """Interface.

    :param name: Full name of digital twin interface.
    :type name: str
    :param properties: List of all properties in an interface.
    :type properties: dict[str, ~protocol.models.Property]
    """

    _attribute_map = {
        "name": {"key": "name", "type": "str"},
        "properties": {"key": "properties", "type": "{Property}"},
    }

    def __init__(self, **kwargs):
        super(Interface, self).__init__(**kwargs)
        self.name = kwargs.get("name", None)
        self.properties = kwargs.get("properties", None)
