repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
