# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class X509CertificateWithInfo(Model):
    """Certificate and Certificate info.

    :param certificate:
    :type certificate: str
    :param info:
    :type info: ~serviceswagger.models.X509CertificateInfo
    """

    _attribute_map = {
        'certificate': {'key': 'certificate', 'type': 'str'},
        'info': {'key': 'info', 'type': 'X509CertificateInfo'},
    }

    def __init__(self, certificate=None, info=None):
        self.certificate = certificate
        self.info = info
