from mcr.microsoft.com/mirror/docker/library/python:3.10-slim-buster

RUN apt update \
    && apt install -y \
        iptables \
    && apt clean

WORKDIR /sdk
COPY requirements_test.txt .
RUN pip install -r requirements_test.txt
COPY . .
RUN python ./scripts/env_setup.py --no_dev

