# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .iot_hub_gateway_service_ap_is20190630 import IotHubGatewayServiceAPIs20190630
from .version import VERSION

__all__ = ['IotHubGatewayServiceAPIs20190630']

__version__ = VERSION

