# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .device_authentication_mechanism import DeviceAuthenticationMechanism


class AutoGeneratedSymmetricKeyDeviceAuthenticationMechanism(DeviceAuthenticationMechanism):
    """Auto-generated Symmetric Key authentication method. Device will have the
    symmetric key auto generated by the service.

    All required parameters must be populated in order to send to Azure.

    :param device_authentication_type: Required. Constant filled by server.
    :type device_authentication_type: str
    :param length: The desired length for autogenerated symmetric key in
     bytes.
    :type length: int
    """

    _validation = {"device_authentication_type": {"required": True}}

    _attribute_map = {
        "device_authentication_type": {"key": "deviceAuthenticationType", "type": "str"},
        "length": {"key": "length", "type": "int"},
    }

    def __init__(self, **kwargs):
        super(AutoGeneratedSymmetricKeyDeviceAuthenticationMechanism, self).__init__(**kwargs)
        self.length = kwargs.get("length", None)
        self.device_authentication_type = "AutoGeneratedSymmetricKeyDeviceAuthenticationMechanism"
