# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CertificateAuthorityQueryResponse(Model):
    """CertificateAuthorityQueryResponse.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar values: The query results.
    :vartype values: list[~protocol.models.CertificateAuthority]
    :ivar continuation: The continuation token for query next api.
    :vartype continuation: ~protocol.models.QueryNext
    """

    _validation = {"values": {"readonly": True}, "continuation": {"readonly": True}}

    _attribute_map = {
        "values": {"key": "values", "type": "[CertificateAuthority]"},
        "continuation": {"key": "continuation", "type": "QueryNext"},
    }

    def __init__(self, **kwargs):
        super(CertificateAuthorityQueryResponse, self).__init__(**kwargs)
        self.values = None
        self.continuation = None
