# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CertificateMetadata(Model):
    """CertificateMetadata.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar subject_name:
    :vartype subject_name: str
    :ivar sha1_thumbprint:
    :vartype sha1_thumbprint: str
    :ivar sha256_thumbprint:
    :vartype sha256_thumbprint: str
    :ivar issuer_name:
    :vartype issuer_name: str
    :ivar not_before_utc:
    :vartype not_before_utc: datetime
    :ivar not_after_utc:
    :vartype not_after_utc: datetime
    :ivar serial_number:
    :vartype serial_number: str
    :ivar version:
    :vartype version: int
    """

    _validation = {
        "subject_name": {"readonly": True},
        "sha1_thumbprint": {"readonly": True},
        "sha256_thumbprint": {"readonly": True},
        "issuer_name": {"readonly": True},
        "not_before_utc": {"readonly": True},
        "not_after_utc": {"readonly": True},
        "serial_number": {"readonly": True},
        "version": {"readonly": True},
    }

    _attribute_map = {
        "subject_name": {"key": "subjectName", "type": "str"},
        "sha1_thumbprint": {"key": "sha1Thumbprint", "type": "str"},
        "sha256_thumbprint": {"key": "sha256Thumbprint", "type": "str"},
        "issuer_name": {"key": "issuerName", "type": "str"},
        "not_before_utc": {"key": "notBeforeUtc", "type": "iso-8601"},
        "not_after_utc": {"key": "notAfterUtc", "type": "iso-8601"},
        "serial_number": {"key": "serialNumber", "type": "str"},
        "version": {"key": "version", "type": "int"},
    }

    def __init__(self, **kwargs) -> None:
        super(CertificateMetadata, self).__init__(**kwargs)
        self.subject_name = None
        self.sha1_thumbprint = None
        self.sha256_thumbprint = None
        self.issuer_name = None
        self.not_before_utc = None
        self.not_after_utc = None
        self.serial_number = None
        self.version = None
