# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceRecord(Model):
    """DeviceRecord.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar device_id: Name of the individual device. A Case-insensitive string
     (up to 128 characters long) of ASCII 7-bit alphanumeric characters plus
     certain special characters : . _ -. No special characters allowed at start
     or end.
    :vartype device_id: str
    :param is_edge: If set to {True} will provision the device as edge device.
     Default value: False .
    :type is_edge: bool
    :param status: The status for this device. Setting to
     {DeviceStatus.Disabled} will block provisioning the device with this
     authentication. Possible values include: 'enabled', 'disabled'. Default
     value: "enabled" .
    :type status: str or ~protocol.models.enum
    :param authentication_mechanisms: Required. Authentication mechanism used
     by the device to provision.
    :type authentication_mechanisms:
     list[~protocol.models.DeviceAuthenticationMechanism]
    :ivar device_group_name: Name of the device group of which this device is
     a member.
    :vartype device_group_name: str
    :ivar desired_hub_device_id: Device Id to be used in IoT Hub during device
     provisioning.
    :vartype desired_hub_device_id: str
    :ivar group_record_name: If set, this device record is auto-created from
     the corresponding group record.
    :vartype group_record_name: str
    :ivar created_date_time_utc: The DateTime this resource was created in
     UTC.
    :vartype created_date_time_utc: datetime
    :ivar last_updated_date_time_utc: The DateTime this resource was last
     updated in UTC.
    :vartype last_updated_date_time_utc: datetime
    :ivar e_tag: The ETag of the device record.
    :vartype e_tag: str
    """

    _validation = {
        "device_id": {"readonly": True},
        "authentication_mechanisms": {"required": True},
        "device_group_name": {"readonly": True},
        "desired_hub_device_id": {"readonly": True},
        "group_record_name": {"readonly": True},
        "created_date_time_utc": {"readonly": True},
        "last_updated_date_time_utc": {"readonly": True},
        "e_tag": {"readonly": True},
    }

    _attribute_map = {
        "device_id": {"key": "deviceId", "type": "str"},
        "is_edge": {"key": "isEdge", "type": "bool"},
        "status": {"key": "status", "type": "str"},
        "authentication_mechanisms": {
            "key": "authenticationMechanisms",
            "type": "[DeviceAuthenticationMechanism]",
        },
        "device_group_name": {"key": "deviceGroupName", "type": "str"},
        "desired_hub_device_id": {"key": "desiredHubDeviceId", "type": "str"},
        "group_record_name": {"key": "groupRecordName", "type": "str"},
        "created_date_time_utc": {"key": "createdDateTimeUtc", "type": "iso-8601"},
        "last_updated_date_time_utc": {"key": "lastUpdatedDateTimeUtc", "type": "iso-8601"},
        "e_tag": {"key": "eTag", "type": "str"},
    }

    def __init__(self, **kwargs):
        super(DeviceRecord, self).__init__(**kwargs)
        self.device_id = None
        self.is_edge = kwargs.get("is_edge", False)
        self.status = kwargs.get("status", "enabled")
        self.authentication_mechanisms = kwargs.get("authentication_mechanisms", None)
        self.device_group_name = None
        self.desired_hub_device_id = None
        self.group_record_name = None
        self.created_date_time_utc = None
        self.last_updated_date_time_utc = None
        self.e_tag = None
