# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceGroup(Model):
    """DeviceGroup.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar name: Name of the device group. A Case-insensitive string (up to 128
     characters long) of ASCII 7-bit alphanumeric characters plus certain
     special characters : . _ -. No special characters allowed at start or end.
    :vartype name: str
    :param provisioning_settings_name: Required. The Name of the provisioning
     settings to apply to this device group.
    :type provisioning_settings_name: str
    :ivar created_date_time_utc: The DateTime this resource was created in
     UTC.
    :vartype created_date_time_utc: datetime
    :ivar last_updated_date_time_utc: The DateTime this resource was last
     updated in UTC.
    :vartype last_updated_date_time_utc: datetime
    :ivar e_tag: The ETag of the device group.
    :vartype e_tag: str
    """

    _validation = {
        "name": {"readonly": True},
        "provisioning_settings_name": {"required": True},
        "created_date_time_utc": {"readonly": True},
        "last_updated_date_time_utc": {"readonly": True},
        "e_tag": {"readonly": True},
    }

    _attribute_map = {
        "name": {"key": "name", "type": "str"},
        "provisioning_settings_name": {"key": "provisioningSettingsName", "type": "str"},
        "created_date_time_utc": {"key": "createdDateTimeUtc", "type": "iso-8601"},
        "last_updated_date_time_utc": {"key": "lastUpdatedDateTimeUtc", "type": "iso-8601"},
        "e_tag": {"key": "eTag", "type": "str"},
    }

    def __init__(self, **kwargs):
        super(DeviceGroup, self).__init__(**kwargs)
        self.name = None
        self.provisioning_settings_name = kwargs.get("provisioning_settings_name", None)
        self.created_date_time_utc = None
        self.last_updated_date_time_utc = None
        self.e_tag = None
