# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .assignment_method import AssignmentMethod


class GeoLatencyAssignmentMethod(AssignmentMethod):
    """Devices are provisioned to an IoT hub with the lowest latency to the
    device.
    If multiple linked IoT hubs would provide the same lowest latency, the
    provisioning service hashes devices across those hubs.

    All required parameters must be populated in order to send to Azure.

    :param assignment_type: Required. Constant filled by server.
    :type assignment_type: str
    :param target_hubs: The list of IoT hubs the device(s) in this resource
     can be assigned to.
    :type target_hubs: list[str]
    """

    _validation = {"assignment_type": {"required": True}}

    _attribute_map = {
        "assignment_type": {"key": "assignmentType", "type": "str"},
        "target_hubs": {"key": "targetHubs", "type": "[str]"},
    }

    def __init__(self, **kwargs):
        super(GeoLatencyAssignmentMethod, self).__init__(**kwargs)
        self.target_hubs = kwargs.get("target_hubs", None)
        self.assignment_type = "GeoLatencyAssignmentMethod"
