# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GroupRecord(Model):
    """GroupRecord.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar name: Name of the group record. A Case-insensitive string (up to 128
     characters long) of ASCII 7-bit alphanumeric characters plus certain
     special characters : . _ -. No special characters allowed at start or end.
    :vartype name: str
    :param is_edge: If set to {True} will provision the devices from this
     group as edge devices. Default value: False .
    :type is_edge: bool
    :param status: The status for this group. Setting to
     {DeviceStatus.Disabled} will block provisioning for devices with this
     group authentication. Possible values include: 'enabled', 'disabled'.
     Default value: "enabled" .
    :type status: str or ~protocol.models.enum
    :param authentication_mechanisms: Required. The authentication mechanism
     used by this group of devices to provision.
    :type authentication_mechanisms:
     list[~protocol.models.GroupAuthenticationMechanism]
    :ivar device_group_name: Name of the device group of which this device is
     a member.
    :vartype device_group_name: str
    :ivar created_date_time_utc: The DateTime this resource was created in
     UTC.
    :vartype created_date_time_utc: datetime
    :ivar last_updated_date_time_utc: The DateTime this resource was last
     updated in UTC.
    :vartype last_updated_date_time_utc: datetime
    :ivar e_tag: The ETag of the group record.
    :vartype e_tag: str
    """

    _validation = {
        "name": {"readonly": True},
        "authentication_mechanisms": {"required": True},
        "device_group_name": {"readonly": True},
        "created_date_time_utc": {"readonly": True},
        "last_updated_date_time_utc": {"readonly": True},
        "e_tag": {"readonly": True},
    }

    _attribute_map = {
        "name": {"key": "name", "type": "str"},
        "is_edge": {"key": "isEdge", "type": "bool"},
        "status": {"key": "status", "type": "str"},
        "authentication_mechanisms": {
            "key": "authenticationMechanisms",
            "type": "[GroupAuthenticationMechanism]",
        },
        "device_group_name": {"key": "deviceGroupName", "type": "str"},
        "created_date_time_utc": {"key": "createdDateTimeUtc", "type": "iso-8601"},
        "last_updated_date_time_utc": {"key": "lastUpdatedDateTimeUtc", "type": "iso-8601"},
        "e_tag": {"key": "eTag", "type": "str"},
    }

    def __init__(
        self, *, authentication_mechanisms, is_edge: bool = False, status="enabled", **kwargs
    ) -> None:
        super(GroupRecord, self).__init__(**kwargs)
        self.name = None
        self.is_edge = is_edge
        self.status = status
        self.authentication_mechanisms = authentication_mechanisms
        self.device_group_name = None
        self.created_date_time_utc = None
        self.last_updated_date_time_utc = None
        self.e_tag = None
