# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LinkedHub(Model):
    """The linked hub.

    You probably want to use the sub-classes and not this class directly. Known
    sub-classes are: ConnectionStringLinkedHub

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar name: Name of the linked hub. A Case-insensitive string (up to 128
     characters long) of ASCII 7-bit alphanumeric characters plus certain
     special characters : . _ -. No special characters allowed at start or end.
    :vartype name: str
    :ivar created_date_time_utc: The DateTime this resource was created in
     UTC.
    :vartype created_date_time_utc: datetime
    :ivar last_updated_date_time_utc: The DateTime this resource was last
     updated in UTC.
    :vartype last_updated_date_time_utc: datetime
    :ivar e_tag: The ETag of the linked hub.
    :vartype e_tag: str
    :param linked_hub_type: Required. Constant filled by server.
    :type linked_hub_type: str
    """

    _validation = {
        "name": {"readonly": True},
        "created_date_time_utc": {"readonly": True},
        "last_updated_date_time_utc": {"readonly": True},
        "e_tag": {"readonly": True},
        "linked_hub_type": {"required": True},
    }

    _attribute_map = {
        "name": {"key": "name", "type": "str"},
        "created_date_time_utc": {"key": "createdDateTimeUtc", "type": "iso-8601"},
        "last_updated_date_time_utc": {"key": "lastUpdatedDateTimeUtc", "type": "iso-8601"},
        "e_tag": {"key": "eTag", "type": "str"},
        "linked_hub_type": {"key": "linkedHubType", "type": "str"},
    }

    _subtype_map = {"linked_hub_type": {"ConnectionStringLinkedHub": "ConnectionStringLinkedHub"}}

    def __init__(self, **kwargs):
        super(LinkedHub, self).__init__(**kwargs)
        self.name = None
        self.created_date_time_utc = None
        self.last_updated_date_time_utc = None
        self.e_tag = None
        self.linked_hub_type = None
