# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProvisioningRecord(Model):
    """ProvisioningRecord.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar device_id: Device Id.
    :vartype device_id: str
    :ivar group_record_id: Group record Id.
    :vartype group_record_id: str
    :ivar assigned_hub: Assigned IoT Hub.
    :vartype assigned_hub: str
    :ivar assigned_from_provisioning_settings: Name of provisioning settings
     used to assign this device to an IoT hub.
    :vartype assigned_from_provisioning_settings: str
    :ivar status: Provisioning status. Possible values include: 'unassigned',
     'assigning', 'assigned', 'failed', 'disabled'. Default value: "unassigned"
     .
    :vartype status: str or ~protocol.models.enum
    :ivar substatus: Sub status for 'Assigned' devices. Possible values
     include - 'initialAssignment': Device has been assigned to an IoT hub for
     the first time, 'deviceDataMigrated': Device has been assigned to a
     different IoT hub and its device data was migrated from the previously
     assigned IoT hub. Device data was removed from the previously assigned IoT
     hub, 'deviceDataReset':  Device has been assigned to a different IoT hub
     and its device data was populated from the initial state stored in the
     enrollment. Device data was removed from the previously assigned IoT hub.
     Possible values include: 'initialAssignment', 'deviceDataMigrated',
     'deviceDataReset'
    :vartype substatus: str or ~protocol.models.enum
    :ivar payload: Custom data returned from the web hook to the device.
    :vartype payload: object
    :ivar authentication_metadata: Authentication metadata.
    :vartype authentication_metadata: ~protocol.models.AuthenticationMetadata
    :ivar issued_x509_certificate: Certificate issued during device
     provisioning.
    :vartype issued_x509_certificate: ~protocol.models.CertificateMetadata
    :ivar error_code: Error code.
    :vartype error_code: int
    :ivar error_message: Error message.
    :vartype error_message: str
    :ivar created_date_time_utc: The DateTime this resource was created in
     UTC.
    :vartype created_date_time_utc: datetime
    :ivar last_updated_date_time_utc: The DateTime this resource was last
     updated in UTC.
    :vartype last_updated_date_time_utc: datetime
    """

    _validation = {
        "device_id": {"readonly": True},
        "group_record_id": {"readonly": True},
        "assigned_hub": {"readonly": True},
        "assigned_from_provisioning_settings": {"readonly": True},
        "status": {"readonly": True},
        "substatus": {"readonly": True},
        "payload": {"readonly": True},
        "authentication_metadata": {"readonly": True},
        "issued_x509_certificate": {"readonly": True},
        "error_code": {"readonly": True},
        "error_message": {"readonly": True},
        "created_date_time_utc": {"readonly": True},
        "last_updated_date_time_utc": {"readonly": True},
    }

    _attribute_map = {
        "device_id": {"key": "deviceId", "type": "str"},
        "group_record_id": {"key": "groupRecordId", "type": "str"},
        "assigned_hub": {"key": "assignedHub", "type": "str"},
        "assigned_from_provisioning_settings": {
            "key": "assignedFromProvisioningSettings",
            "type": "str",
        },
        "status": {"key": "status", "type": "str"},
        "substatus": {"key": "substatus", "type": "str"},
        "payload": {"key": "payload", "type": "object"},
        "authentication_metadata": {
            "key": "authenticationMetadata",
            "type": "AuthenticationMetadata",
        },
        "issued_x509_certificate": {"key": "issuedX509Certificate", "type": "CertificateMetadata"},
        "error_code": {"key": "errorCode", "type": "int"},
        "error_message": {"key": "errorMessage", "type": "str"},
        "created_date_time_utc": {"key": "createdDateTimeUtc", "type": "iso-8601"},
        "last_updated_date_time_utc": {"key": "lastUpdatedDateTimeUtc", "type": "iso-8601"},
    }

    def __init__(self, **kwargs):
        super(ProvisioningRecord, self).__init__(**kwargs)
        self.device_id = None
        self.group_record_id = None
        self.assigned_hub = None
        self.assigned_from_provisioning_settings = None
        self.status = None
        self.substatus = None
        self.payload = None
        self.authentication_metadata = None
        self.issued_x509_certificate = None
        self.error_code = None
        self.error_message = None
        self.created_date_time_utc = None
        self.last_updated_date_time_utc = None
