# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .authentication_metadata import AuthenticationMetadata


class SymmetricKeyAuthenticationMetadata(AuthenticationMetadata):
    """SymmetricKeyAuthenticationMetadata.

    All required parameters must be populated in order to send to Azure.

    :param authentication_metadata_type: Required. Constant filled by server.
    :type authentication_metadata_type: str
    """

    _validation = {"authentication_metadata_type": {"required": True}}

    _attribute_map = {
        "authentication_metadata_type": {"key": "authenticationMetadataType", "type": "str"}
    }

    def __init__(self, **kwargs):
        super(SymmetricKeyAuthenticationMetadata, self).__init__(**kwargs)
        self.authentication_metadata_type = "SymmetricKeyAuthenticationMetadata"
