# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .device_authentication_mechanism_py3 import DeviceAuthenticationMechanism


class SymmetricKeyDeviceAuthenticationMechanism(DeviceAuthenticationMechanism):
    """SymmetricKeyDeviceAuthenticationMechanism.

    All required parameters must be populated in order to send to Azure.

    :param device_authentication_type: Required. Constant filled by server.
    :type device_authentication_type: str
    :param symmetric_key: Required. The symmetric key used by device.
    :type symmetric_key: str
    """

    _validation = {
        "device_authentication_type": {"required": True},
        "symmetric_key": {"required": True},
    }

    _attribute_map = {
        "device_authentication_type": {"key": "deviceAuthenticationType", "type": "str"},
        "symmetric_key": {"key": "symmetricKey", "type": "str"},
    }

    def __init__(self, *, symmetric_key: str, **kwargs) -> None:
        super(SymmetricKeyDeviceAuthenticationMechanism, self).__init__(**kwargs)
        self.symmetric_key = symmetric_key
        self.device_authentication_type = "SymmetricKeyDeviceAuthenticationMechanism"
