# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .group_authentication_mechanism_py3 import GroupAuthenticationMechanism


class X509CAReferenceGroupAuthenticationMechanism(GroupAuthenticationMechanism):
    """X509 authentication method. Devices in this device group have this signing
    certificate in their certificate chain.

    All required parameters must be populated in order to send to Azure.

    :param group_authentication_type: Required. Constant filled by server.
    :type group_authentication_type: str
    :param certificate_authority_name: Required. The certificate authority
     name.
    :type certificate_authority_name: str
    """

    _validation = {
        "group_authentication_type": {"required": True},
        "certificate_authority_name": {"required": True},
    }

    _attribute_map = {
        "group_authentication_type": {"key": "groupAuthenticationType", "type": "str"},
        "certificate_authority_name": {"key": "certificateAuthorityName", "type": "str"},
    }

    def __init__(self, *, certificate_authority_name: str, **kwargs) -> None:
        super(X509CAReferenceGroupAuthenticationMechanism, self).__init__(**kwargs)
        self.certificate_authority_name = certificate_authority_name
        self.group_authentication_type = "X509CAReferenceGroupAuthenticationMechanism"
