resources:
- repo: self
#Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases
jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu 20.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'

  - script: 'python scripts/env_setup.py --no_dev'
    displayName: 'Prepare environment (install packages + dev dependencies + test dependencies + tools)'

  - script: 'python -m pip install cryptography'
    displayName: 'Install pyca/cryptography for X509 functionality'

  - script: |
      cd $(Agent.WorkFolder)
      cd ..
      touch .rnd
    displayName: 'create RANDFILE file (needed to store seed data) separately due to openssl version issues in the pipeline'

  - script: |
      cd $(Build.SourcesDirectory)/tests/e2e/provisioning_e2e
      pytest --junitxml=junit/dps-e2e-test-results.xml
    displayName: 'Run Specified E2E Test with env variables'

    env:
      IOTHUB_CONNECTION_STRING: $(PYTHONV2JAN-IOTHUB-CONNECTION-STRING)
      IOTHUB_EVENTHUB_CONNECTION_STRING: $(PYTHONV2JAN-IOTHUB-EVENTHUB-CONNECTION-STRING)
      IOTHUB_CA_ROOT_CERT: $(PYTHONV2JAN-LINUX-IOTHUB-CA-ROOT-CERT)
      IOTHUB_CA_ROOT_CERT_KEY: $(PYTHONV2JAN-LINUX-IOTHUB-CA-ROOT-CERT-KEY)
      STORAGE_CONNECTION_STRING: $(PYTHONV2JAN-IOTHUB-STORAGE-CONNECTION-STRING)

      PROVISIONING_DEVICE_ENDPOINT: $(PYTHONV2JAN-LINUX-DPS-DEVICE-ENDPOINT)
      PROVISIONING_SERVICE_CONNECTION_STRING: $(PYTHONV2JAN-DPS-CONNECTION-STRING)
      PROVISIONING_DEVICE_IDSCOPE: $(PYTHONV2JAN-LINUX-DPS-ID-SCOPE)

      PROVISIONING_ROOT_CERT: $(PYTHONV2JAN-LINUX-IOT-PROVISIONING-ROOT-CERT)
      PROVISIONING_ROOT_CERT_KEY: $(PYTHONV2JAN-LINUX-IOT-PROVISIONING-ROOT-CERT-KEY)
      PROVISIONING_ROOT_PASSWORD: $(PYTHONV2JAN-LINUX-ROOT-CERT-PASSWORD)
      PYTHONUNBUFFERED: True

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: always()
    inputs:
      testResultsFiles: '**/dps-e2e-test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
