resources:
- repo: self
#Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases

stages:
- stage: setup
  jobs:
  - job: create_azure_resources
    pool:
      vmImage: 'ubuntu-24.04'
    steps:
    - script: |
        sudo apt-get install -y uuid
        AZURE_RESOURCE_GROUP="iotpythondpse2e$(uuid | tr -d '-')"
        AZURE_IOTHUB_NAME="iotpythondpse2e$(uuid | tr -d '-')"
        AZURE_DPS_NAME="iotpythondpse2e$(uuid | tr -d '-')"

        # Export variables to other stages/jobs/steps.
        echo "##vso[task.setvariable variable=AZURE_RESOURCE_GROUP;isOutput=true]$AZURE_RESOURCE_GROUP"
        echo "##vso[task.setvariable variable=AZURE_IOTHUB_NAME;isOutput=true]$AZURE_IOTHUB_NAME"
        echo "##vso[task.setvariable variable=AZURE_DPS_NAME;isOutput=true]$AZURE_DPS_NAME"
      name: setResourceNames
      displayName: Set Azure Resource Names

    - script: |
        set -e

        mkdir certs csr newcerts private
        touch index.txt

        openssl rand -hex 16 > serial

        cat > ./openssl_root_ca.cnf << 'EOF_1'
        # OpenSSL root CA configuration file.

        [ ca ]
        default_ca = CA_default

        [ CA_default ]
        # Directory and file locations.
        dir               = .
        certs             = $dir/certs
        crl_dir           = $dir/crl
        new_certs_dir     = $dir/newcerts
        database          = $dir/index.txt
        serial            = $dir/serial
        RANDFILE          = $dir/private/.rand

        # The root key and root certificate.
        private_key       = $dir/private/azure-iot-test-only.root.ca.key.pem
        certificate       = $dir/certs/azure-iot-test-only.root.ca.cert.pem

        # For certificate revocation lists.
        crlnumber         = $dir/crlnumber
        crl               = $dir/crl/azure-iot-test-only.intermediate.crl.pem
        crl_extensions    = crl_ext
        default_crl_days  = 30

        # SHA-1 is deprecated, so use SHA-2 instead.
        default_md        = sha256

        name_opt          = ca_default
        cert_opt          = ca_default
        default_days      = 375
        preserve          = no
        policy            = policy_loose

        [ policy_strict ]
        # The root CA should only sign intermediate certificates that match.
        countryName             = optional
        stateOrProvinceName     = optional
        organizationName        = optional
        organizationalUnitName  = optional
        #commonName              = supplied
        commonName              = optional
        emailAddress            = optional

        [ policy_loose ]
        # Allow the intermediate CA to sign a more diverse range of certificates.
        countryName             = optional
        stateOrProvinceName     = optional
        localityName            = optional
        organizationName        = optional
        organizationalUnitName  = optional
        #commonName              = supplied
        commonName              = optional
        emailAddress            = optional

        [ req ]
        default_bits        = 2048
        distinguished_name  = req_distinguished_name
        string_mask         = utf8only

        # SHA-1 is deprecated, so use SHA-2 instead.
        default_md          = sha256

        # Extension to add when the -x509 option is used.
        x509_extensions     = v3_ca

        [ req_distinguished_name ]
        # See <https://en.wikipedia.org/wiki/Certificate_signing_request>.
        countryName                     = Country Name (2 letter code)
        stateOrProvinceName             = State or Province Name
        localityName                    = Locality Name
        0.organizationName              = Organization Name
        organizationalUnitName          = Organizational Unit Name
        commonName                      = Common Name
        emailAddress                    = Email Address

        # Optionally, specify some defaults.
        countryName_default             = US
        stateOrProvinceName_default     = WA
        localityName_default            =
        0.organizationName_default      = My Organization
        organizationalUnitName_default  =
        emailAddress_default            =

        [ v3_ca ]
        # Extensions for a typical CA.
        subjectKeyIdentifier = hash
        authorityKeyIdentifier = keyid:always,issuer
        basicConstraints = critical, CA:true
        keyUsage = critical, digitalSignature, cRLSign, keyCertSign

        [ v3_intermediate_ca ]
        # Extensions for a typical intermediate CA.
        subjectKeyIdentifier = hash
        authorityKeyIdentifier = keyid:always,issuer
        basicConstraints = critical, CA:true
        keyUsage = critical, digitalSignature, cRLSign, keyCertSign

        [ usr_cert ]
        # Extensions for client certificates.
        basicConstraints = CA:FALSE
        nsComment = "OpenSSL Generated Client Certificate"
        subjectKeyIdentifier = hash
        authorityKeyIdentifier = keyid,issuer
        keyUsage = critical, nonRepudiation, digitalSignature, keyEncipherment
        extendedKeyUsage = clientAuth

        [ server_cert ]
        # Extensions for server certificates.
        basicConstraints = CA:FALSE
        nsComment = "OpenSSL Generated Server Certificate"
        subjectKeyIdentifier = hash
        authorityKeyIdentifier = keyid,issuer:always
        keyUsage = critical, digitalSignature, keyEncipherment
        extendedKeyUsage = serverAuth

        [ crl_ext ]
        # Extension for CRLs.
        authorityKeyIdentifier=keyid:always

        [ ocsp ]
        # Extension for OCSP signing certificates.
        basicConstraints = CA:FALSE
        subjectKeyIdentifier = hash
        authorityKeyIdentifier = keyid,issuer
        keyUsage = critical, digitalSignature
        extendedKeyUsage = critical, OCSPSigning

        EOF_1

        # Root CA Key (create)
        openssl genrsa -aes256 -passout pass:1234 -out ./private/azure-iot-test-only.root.ca.key.pem 4096

        # Root CA Certificate (create)
        openssl req -new -x509 -config ./openssl_root_ca.cnf -passin pass:1234 -key ./private/azure-iot-test-only.root.ca.key.pem -subj '/CN=Azure IoT Hub CA Cert Test Only' -days 30 -sha256 -extensions v3_ca -out ./certs/azure-iot-test-only.root.ca.cert.pem

        export DPS_ROOT_CA_CERT=$(pwd)/certs/azure-iot-test-only.root.ca.cert.pem
        export DPS_ROOT_CA_PK=$(pwd)/private/azure-iot-test-only.root.ca.key.pem
        export DPS_ROOT_CA_PASSWORD=1234

        echo "##vso[task.setvariable variable=DPS_ROOT_CA_CERT;isOutput=true]$DPS_ROOT_CA_CERT"
        echo "##vso[task.setvariable variable=DPS_ROOT_CA_PK;isOutput=true]$DPS_ROOT_CA_PK"
        echo "##vso[task.setvariable variable=DPS_ROOT_CA_PASSWORD;isOutput=true]$DPS_ROOT_CA_PASSWORD"
      name: testCertificates
      displayName: Create Test Certificates
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e

          export AZURE_RESOURCE_GROUP=$(setResourceNames.AZURE_RESOURCE_GROUP)
          export AZURE_IOTHUB_NAME=$(setResourceNames.AZURE_IOTHUB_NAME)
          export AZURE_DPS_NAME=$(setResourceNames.AZURE_DPS_NAME)

          # Create Resource Group
          az group create -g $AZURE_RESOURCE_GROUP -l $(AZURE_REGION)

          # Create Azure IoT Hub
          time az iot hub create -g $AZURE_RESOURCE_GROUP -n $AZURE_IOTHUB_NAME --dla false --mintls 1.2 --partition-count 4 --sku S1

          export IOTHUB_CONNECTION_STRING=$(az iot hub connection-string show -g $AZURE_RESOURCE_GROUP --hub-name $AZURE_IOTHUB_NAME --pn iothubowner --query "connectionString" --output tsv)
          export EVENTHUB_CONNECTION_STRING=$(az iot hub connection-string show -g $AZURE_RESOURCE_GROUP --hub-name $AZURE_IOTHUB_NAME --eh --query "connectionString" --output tsv)

          for i in $(seq 1 11); do
              cg_name="cg$i"
              az iot hub consumer-group create -g "$AZURE_RESOURCE_GROUP" --hub-name "$AZURE_IOTHUB_NAME" --name "$cg_name"
          done

          # Create Device Provisioning service
          time az iot dps create -g $AZURE_RESOURCE_GROUP --name $AZURE_DPS_NAME -l $(AZURE_REGION)
          time az iot dps linked-hub create -g $AZURE_RESOURCE_GROUP --dps-name $AZURE_DPS_NAME --connection-string "$IOTHUB_CONNECTION_STRING"

          export DPS_CONNECTION_STRING=$(az iot dps connection-string show -g $AZURE_RESOURCE_GROUP --name $AZURE_DPS_NAME --pn provisioningserviceowner --query "connectionString" --output tsv)
          export DPS_ID_SCOPE=$(az iot dps show --name $AZURE_DPS_NAME -g $AZURE_RESOURCE_GROUP --query properties.idScope --output tsv)
          export DPS_HOSTNAME=$(az iot dps show --name $AZURE_DPS_NAME -g $AZURE_RESOURCE_GROUP --query properties.deviceProvisioningHostName --output tsv)

          printenv | sort

          # Export variables to other stages/jobs/steps.
          echo "##vso[task.setvariable variable=IOTHUB_CONNECTION_STRING;isOutput=true]$IOTHUB_CONNECTION_STRING"
          echo "##vso[task.setvariable variable=EVENTHUB_CONNECTION_STRING;isOutput=true]$EVENTHUB_CONNECTION_STRING"
          echo "##vso[task.setvariable variable=DPS_CONNECTION_STRING;isOutput=true]$DPS_CONNECTION_STRING"
          echo "##vso[task.setvariable variable=DPS_ID_SCOPE;isOutput=true]$DPS_ID_SCOPE"
          echo "##vso[task.setvariable variable=DPS_HOSTNAME;isOutput=true]$DPS_HOSTNAME"
      displayName: Create IoT Hub & DPS
      name: createAzureResources
- stage: build_and_tests
  jobs:
  - job: 'Test'
    variables:
      IOTHUB_CONNECTION_STRING: $[stageDependencies.setup.create_azure_resources.outputs['createAzureResources.IOTHUB_CONNECTION_STRING']]
      EVENTHUB_CONNECTION_STRING: $[stageDependencies.setup.create_azure_resources.outputs['createAzureResources.EVENTHUB_CONNECTION_STRING']]
      DPS_CONNECTION_STRING: $[stageDependencies.setup.create_azure_resources.outputs['createAzureResources.DPS_CONNECTION_STRING']]
      DPS_ID_SCOPE: $[stageDependencies.setup.create_azure_resources.outputs['createAzureResources.DPS_ID_SCOPE']]
      DPS_HOSTNAME: $[stageDependencies.setup.create_azure_resources.outputs['createAzureResources.DPS_HOSTNAME']]
      DPS_ROOT_CA_CERT: $[stageDependencies.setup.create_azure_resources.outputs['testCertificates.DPS_ROOT_CA_CERT']]
      DPS_ROOT_CA_PK: $[stageDependencies.setup.create_azure_resources.outputs['testCertificates.DPS_ROOT_CA_PK']]
      DPS_ROOT_CA_PASSWORD: $[stageDependencies.setup.create_azure_resources.outputs['testCertificates.DPS_ROOT_CA_PASSWORD']]
    pool:
      vmImage: 'ubuntu-22.04'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        architecture: 'x64'

    - script: 'python scripts/env_setup.py --no_dev'
      displayName: 'Prepare environment (install packages + dev dependencies + test dependencies + tools)'

    - script: 'python -m pip install cryptography'
      displayName: 'Install pyca/cryptography for X509 functionality'

    - script: |
        cd $(Agent.WorkFolder)
        cd ..
        touch .rnd
      displayName: 'create RANDFILE file (needed to store seed data) separately due to openssl version issues in the pipeline'

    - script: |
        printenv | sort
        cd $(Build.SourcesDirectory)/tests/e2e/provisioning_e2e
        pytest --junitxml=junit/dps-e2e-test-results.xml
      displayName: 'Run Specified E2E Test with env variables'

      env:
        IOTHUB_CONNECTION_STRING: $(IOTHUB_CONNECTION_STRING)
        IOTHUB_EVENTHUB_CONNECTION_STRING: $(EVENTHUB_CONNECTION_STRING)

        PROVISIONING_DEVICE_ENDPOINT: $(DPS_HOSTNAME)
        PROVISIONING_SERVICE_CONNECTION_STRING: $(DPS_CONNECTION_STRING)
        PROVISIONING_DEVICE_IDSCOPE: $(DPS_ID_SCOPE)

        PROVISIONING_ROOT_CERT: $(DPS_ROOT_CA_CERT)
        PROVISIONING_ROOT_CERT_KEY: $(DPS_ROOT_CA_PK)
        PROVISIONING_ROOT_PASSWORD: $(DPS_ROOT_CA_PASSWORD)
        PYTHONUNBUFFERED: True

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: always()
      inputs:
        testResultsFiles: '**/dps-e2e-test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
- stage: cleanup
  dependsOn:
  - setup
  - build_and_tests
  condition: always() # Run stage even if the pipeline run is cancelled.
  jobs:
  - job: destroy_azure_resource_group
    condition: always() # Run job even if the pipeline run is cancelled.
    variables:
        AZURE_RESOURCE_GROUP: $[stageDependencies.setup.create_azure_resources.outputs['setResourceNames.AZURE_RESOURCE_GROUP']]
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # set -e

          printenv | sort | grep -i azure

          time az group delete --name $(AZURE_RESOURCE_GROUP) --yes
      displayName: Destroy Azure Resource Group
      condition: always() # Run step even if the pipeline run is cancelled.