name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName) 

jobs:
- job: 'Test'

  strategy:
    maxParallel: 4
    matrix:
      py39_windows_mqtt:
        pv: '3.9'
        transport: 'mqtt'
        imageName: 'windows-latest'
        consumerGroup: 'cg1'
      py39_windows_mqttws:
        pv: '3.9'
        transport: 'mqttws'
        imageName: 'windows-latest'
        consumerGroup: 'cg2'
      py38_linux_mqttws:
        pv: '3.8'
        transport: 'mqttws'
        imageName: 'Ubuntu 20.04'
        consumerGroup: 'cg4'
      py38_linux_mqtt:
        pv: '3.8'
        transport: 'mqtt'
        imageName: 'Ubuntu 20.04'
        consumerGroup: 'cg5'
      py310_linux_mqtt:
        pv: '3.10'
        transport: 'mqtt'
        imageName: 'Ubuntu 20.04'
        consumerGroup: 'cg6'
      py311_linux_mqtt:
        pv: '3.11'
        transport: 'mqtt'
        imageName: 'Ubuntu 20.04'
        consumerGroup: 'cg7'
      py312_linux_mqtt:
        pv: '3.12'
        transport: 'mqtt'
        imageName: 'Ubuntu 20.04'
        consumerGroup: 'cg8'
      py312_linux_mqttws:
        pv: '3.12'
        transport: 'mqttws'
        imageName: 'Ubuntu 20.04'
        consumerGroup: 'cg9'

  pool:
    vmImage: $(imageName)

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pv)
        architecture: 'x64'

    - script: 'python scripts/env_setup.py --no_dev'
      displayName: 'Prepare environment (install packages + dev dependencies + test dependencies + tools)'

    - script: |
        cd $(Build.SourcesDirectory)/tests/e2e/iothub_e2e
        echo "Using consumer group: ${EVENTHUB_CONSUMER_GROUP}"
        pytest --transport=$(transport) --junitxml=junit/TEST-python-e2e.xml -o junit_suite_name="$(Agent.JobName)" 
      displayName: 'E2E Device Client MQTT Connection String'
      env:
        IOTHUB_CONNECTION_STRING: $(IOTHUB-CONNECTION-STRING)
        EVENTHUB_CONNECTION_STRING: $(EVENTHUB-CONNECTION-STRING)
        EVENTHUB_CONSUMER_GROUP: $(consumerGroup)
        PYTHONUNBUFFERED: True

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: always()

