# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .device_provisioning_service_service_runtime_client import DeviceProvisioningServiceServiceRuntimeClient
from .version import VERSION

__all__ = ['DeviceProvisioningServiceServiceRuntimeClient']

__version__ = VERSION

