# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomAllocationDefinition(Model):
    """Custom allocation definition.

    All required parameters must be populated in order to send to Azure.

    :param webhook_url: Required. The webhook URL used for allocation
     requests.
    :type webhook_url: str
    :param api_version: Required. The API version of the provisioning service
     types (such as IndividualEnrollment) sent in the custom allocation
     request. Supported versions include: "2018-09-01-preview"
    :type api_version: str
    """

    _validation = {"webhook_url": {"required": True}, "api_version": {"required": True}}

    _attribute_map = {
        "webhook_url": {"key": "webhookUrl", "type": "str"},
        "api_version": {"key": "apiVersion", "type": "str"},
    }

    def __init__(self, **kwargs):
        super(CustomAllocationDefinition, self).__init__(**kwargs)
        self.webhook_url = kwargs.get("webhook_url", None)
        self.api_version = kwargs.get("api_version", None)
