name: "Set Issue Label"
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@dc881db370e1faa4bcc32ad5d3fadb6d905d8700 # v2.0.2
        with:
          keywords: '[""]'
          labels: '["IoTSDK"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
